"""add category to conversations and score to feedbacks

Revision ID: 77353f73f182
Revises: 20937389d3fd
Create Date: 2025-03-28 20:11:29.021043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77353f73f182'
down_revision = '20937389d3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ### 